apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # change `prometheus` to real endpoint
    url: http://prometheus:9090
    uid: master_prometheus
    isDefault: true
    jsonData:
      timeInterval: 4s
      timeout: 4s
      httpMethod: POST
      prometheusType: Prometheus
      
      
      
