{
 "title": "app",
 "description": "Application Metrics from Envoy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "QPS error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(envoy_redis_command_get_error[1m]) + irate(envoy_redis_command_set_error[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis_QoS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "QPS of Redis",
   "type": "timeseries",
   "description": "p99 Latence of set, get ops",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(envoy_redis_command_get_total[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(envoy_redis_command_set_total[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(envoy_redis_command_get_total[$__interval]) + irate(envoy_redis_command_set_total[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "timeseries",
   "description": "p99 Latence of set, get ops",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (irate(envoy_redis_command_set_latency_bucket[$__interval]))) / 1000",
     "legendFormat": "set"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (irate(envoy_redis_command_get_latency_bucket[$__interval]))) / 1000",
     "legendFormat": "get"
    }
   ]
  }
 ]
}