{
 "title": "Host",
 "description": "Host Metrics from Node Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LLC Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "resctrl_llc_occupancy_bytes{group=\"global\", job=\"resctrl_exporter\", instance=\"worknode:9900\"} / 1024 / 28160",
     "legendFormat": "numa_{{numa}}"
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Context Switch",
   "type": "timeseries",
   "description": "内核上下文切换",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interrupt",
   "type": "timeseries",
   "description": "内核中断数",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_intr_total{instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "thread fork",
   "type": "timeseries",
   "description": "进程增量",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_forks_total{instance=\"worknode:9100\",job=\"node_exporter\"}[$__interval])",
     "legendFormat": "fork"
    }
   ]
  },
  {
   "title": "Syscall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(ebpf_exporter_syscalls_total{job=\"ebpf_exporter\", instance=\"worknode:9435\"}[$__interval])",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Usage",
   "type": "timeseries",
   "description": "CPU各个模块利用率",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by(mode)(rate(node_cpu_seconds_total{instance=\"worknode:9100\",job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Scaling Freq MHz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"worknode:9100\", job=\"node_exporter\", cpu=\"131\"} / 1000 / 1000",
     "legendFormat": "cpu131"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_hertz) / 1000 / 1000",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "cpu  load per cores",
   "type": "timeseries",
   "description": "每核心的负载进程数，大于1时表示有排队",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "node_load5 / on (instance) (count by (instance) (node_cpu_seconds_total{mode=\"idle\",instance=\"worknode:9100\",job=\"node_exporter\"}))",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load1 / on (instance) (count by (instance) (node_cpu_seconds_total{mode=\"idle\",instance=\"worknode:9100\",job=\"node_exporter\"}))",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load15 / on (instance) (count by (instance) (node_cpu_seconds_total{mode=\"idle\",instance=\"worknode:9100\",job=\"node_exporter\"}))",
     "legendFormat": "load15"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Usage Not Contain Cache And Buffer",
   "type": "timeseries",
   "description": "内存利用率，不包含cache和buffer",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "100 * (1- (node_memory_MemFree_bytes{instance=\"worknode:9100\", job=\"node_exporter\"}\r\n + node_memory_Buffers_bytes{instance=\"worknode:9100\", job=\"node_exporter\"}\r\n + node_memory_Cached_bytes{instance=\"worknode:9100\", job=\"node_exporter\"}) \r\n / node_memory_MemTotal_bytes{instance=\"worknode:9100\", job=\"node_exporter\"})",
     "legendFormat": "not_contain_cache_and_buffer"
    }
   ]
  },
  {
   "title": "Usage Contain Cache And Buffer",
   "type": "timeseries",
   "description": "内存利用率，包含内存cache和buffer",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "100 * (1-(node_memory_MemFree_bytes{instance=\"worknode:9100\", job=\"node_exporter\"}) \r\n / node_memory_MemTotal_bytes{instance=\"worknode:9100\", job=\"node_exporter\"})",
     "legendFormat": "contain_cache_and_buffer"
    }
   ]
  },
  {
   "title": "Mem Bandwidth",
   "type": "timeseries",
   "description": "内存带宽",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(resctrl_mem_bandwidth_local_bytes{group=\"global\", job=\"resctrl_exporter\", instance=\"worknode:9900\"}[$__interval]) / 1024 / 1024",
     "legendFormat": "local_numa_{{numa}}"
    },
    {
     "expr": "rate(resctrl_mem_bandwidth_total_bytes{group=\"global\", job=\"resctrl_exporter\", instance=\"worknode:9900\"}[$__interval]) / 1024 / 1024",
     "legendFormat": "total_numa_{{numa}}"
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Bytes",
   "type": "timeseries",
   "description": "主机网络接收和发送",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"enp26s0f.*\", instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"enp26s0f.*\", instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "description": "主机网络接收和发送包",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_packets_total{instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_packets_total{instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "transmit"
    }
   ]
  },
  { "title": "Block IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Bytes",
   "type": "timeseries",
   "description": "主机磁盘io的bytes",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"worknode:9100\", job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "description": "主机当期那磁盘io时间",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total[$__interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total[$__interval]))",
     "legendFormat": "write"
    }
   ]
  }
 ]
}