FROM docker.io/golang:1.20.5-alpine3.18 AS build

ENV LIBXML2_VER=2.11.4

RUN apk add ca-certificates g++ git libnl3-dev linux-headers make libvirt-dev libvirt python3 python3-dev && \
    wget https://download.gnome.org/sources/libxml2/2.11/libxml2-${LIBXML2_VER}.tar.xz -P /tmp && \
    tar -xf /tmp/libxml2-${LIBXML2_VER}.tar.xz -C /tmp/ && \
    cd /tmp/libxml2-${LIBXML2_VER} && \
    ./configure && \
    make -j$(nproc) && \
    make install